name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: create res folder
        run: mkdir -p res/Data
      - name: decode data
        run: |
          echo '${{secrets.DATA1}}' | base64 -d > /home/runner/work/EDA_python/EDA_python/src/res/Data/Data_CH001_000.abf
          echo '${{secrets.DATA2}}' | base64 -d > /home/runner/work/EDA_python/EDA_python/src/res/Data/Data_CH002_000.abf
          echo '${{secrets.DATA3}}' | base64 -d > /home/runner/work/EDA_python/EDA_python/src/res/Data/Data_CH003_000.abf
          echo '${{secrets.DATA4}}' | base64 -d > /home/runner/work/EDA_python/EDA_python/src/res/Data/Data_CH004_000.abf
          echo '${{secrets.EDH}}' | base64 -d > /home/runner/work/EDA_python/EDA_python/src/res/Data/Data.edh
          
      - name: Test with pytest
        run: |
          pytest
